### ISSUE TITLE
fileを押すと表示されず固まる現象

### ISSUE THREAD

**Issue by HACKShinn1204** [dn5-run/BaCon#13]
v0.3.3のアップデートでfileを見る？機能が追加されたがそのfileのボタンを押すとすべてが固まりServersには戻れるがボタンを押しても反応しなくなる。そして停止ボタンはずっとぐるぐる

file↓
![image](https://user-images.githubusercontent.com/86346049/159116306-c17c26ca-84d8-40e8-b8f7-aa8626548e03.png)

ぼったーん↓
![image](https://user-images.githubusercontent.com/86346049/159116320-2681e94a-a57c-430d-933c-328e86e5b676.png)

**Comment by HACKShinn1204** [comment]
あとなんかの警告
![image](https://user-images.githubusercontent.com/86346049/159116344-0270fb5e-d4c9-4726-9301-781e8fdd4dda.png)

**Comment by ddPn08** [comment]
たまに起きる現象らしいのでのちのち（リリースまでには）修正します。

**Comment by HACKShinn1204** [comment]
おｋ－ー
